In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
points = torch.ones(6)

points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])

In [14]:
img_t = torch.randn(3, 5, 5)  # shape for [c, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [15]:
batch_t = torch.randn(2, 3, 5, 5)  # shape for [batch, c, rows, columns]

In [16]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [18]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)  # new dimension
img_weights = (img_t * unsqueezed_weights)  # broadcast
batch_weights = (batch_t * unsqueezed_weights)  # broadcast
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [19]:
weights.shape

torch.Size([3])

In [22]:
weighted_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weighted_named

/var/folders/47/z1b86_2x0cxf_y272xj6tnkh0000gn/T/ipykernel_46830/374424677.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1708025541661/work/c10/core/TensorImpl.h:1911.)
  weighted_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [25]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print(img_named.shape, img_named.names)
print(batch_named.shape, batch_named.names)

torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [28]:
weights_aligned = weighted_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [30]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [31]:
img_named.shape, weights_aligned.shape

(torch.Size([3, 5, 5]), torch.Size([3, 1, 1]))

In [32]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [35]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [36]:
short_points.dtype

torch.int16

In [38]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
short_points.dtype

torch.int16

In [39]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [40]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)  # 0: the first dimension; 1: the second dimension
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [41]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage

<bound method Tensor.storage of tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])>

In [43]:
points.storage()

/var/folders/47/z1b86_2x0cxf_y272xj6tnkh0000gn/T/ipykernel_46830/2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [44]:
points_storage = points.storage()
points_storage[0]

4.0

In [46]:
points.storage()[1]

1.0

In [47]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [48]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [49]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [50]:
second_point.size()

torch.Size([2])

In [51]:
second_point.shape

torch.Size([2])

In [52]:
points.stride()

(2, 1)

In [56]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="mps")

In [57]:
points_gpu = points.to(device="mps")

In [58]:
points_cpu = points_gpu.to(device="cpu")

In [59]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [60]:
torch.save(points, "points_file.t")

In [61]:
with open("points_file_2_test.t", "wb") as f:
    torch.save(points, f)

In [62]:
points = torch.load("points_file.t")

In [63]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
with open("points_file.t", "rb") as f:
    points = torch.load(f)

In [67]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
import h5py

In [69]:
f = h5py.File("hdf5", "w")
dset = f.create_dataset("coords", data=points.numpy())
f.close()

In [70]:
f = h5py.File("hdf5", "r")
dset = f["coords"]
last_points = dset[-2:]

In [72]:
last_points = torch.from_numpy(dset[-2:])
last_points
f.close()

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point

tensor([5., 3.])

In [74]:
second_point.storage_offset()

2

In [75]:
second_point.size()

torch.Size([2])

In [76]:
points.stride()

(2, 1)